package org.logstashplugins.java.fst;

public class TestData {
	public static final String FST_SIMPLE="java.lang.ClassNotFoundException: com.test.solutions.google.opf.product.orch.actions.agreement.ActivateContractChanges_Fail\r\n" + 
			"	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:297)\r\n" + 
			"	at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:270)\r\n" + 
			"	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)\r\n" + 
			"	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)\r\n" + 
			"	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:179)\r\n" + 
			"	at java.lang.Class.forName0(Native Method)\r\n" + 
			"	at java.lang.Class.forName(Class.java:195)\r\n" + 
			"	at com.test.platform.orchestrator.core.actions.synchronous.SynchronousJavaActionExecutor.getActionClassInstance(SynchronousJavaActionExecutor.java:65)\r\n" + 
			"	at com.test.platform.orchestrator.core.actions.synchronous.SynchronousJavaActionExecutor.executeAction(SynchronousJavaActionExecutor.java:79)\r\n" + 
			"	at com.test.platform.orchestrator.core.orch.OrchestrateMultipleTasksAction.handleTask(OrchestrateMultipleTasksAction.java:185)\r\n" + 
			"	at com.test.platform.orchestrator.core.orch.MultipleTaskHandler.executeTaskByHandler(MultipleTaskHandler.java:276)\r\n" + 
			"	at com.test.platform.orchestrator.core.orch.MultipleTaskHandler.handleMultipleTasks(MultipleTaskHandler.java:156)\r\n" + 
			"	at com.test.platform.orchestrator.core.orch.MultipleTaskExecutor.orchestrateMultipleTasks(MultipleTaskExecutor.java:42)\r\n" + 
			"	at com.test.platform.orchestrator.core.orch.ProcessExecutor.orchestrateTasks(ProcessExecutor.java:313)\r\n" + 
			"	at com.test.platform.orchestrator.core.orch.ProcessExecutor.orchestrateProcess(ProcessExecutor.java:152)\r\n" + 
			"	at com.test.platform.orchestrator.core.flow.FlowManager$7.continueProcessExecution(FlowManager.java:1270)\r\n" + 
			"	at com.test.platform.orchestrator.core.flow.FlowManager$7.handleProcess(FlowManager.java:1164)\r\n" + 
			"	at com.test.platform.orchestrator.core.orch.ProcessHandler.handleProcess(ProcessHandler.java:110)\r\n" + 
			"	at com.test.platform.orchestrator.core.flow.FlowManager.performCompleteAsyncTask(FlowManager.java:1107)\r\n" + 
			"	at com.test.platform.orchestrator.core.flow.FlowManager$2.processMessage(FlowManager.java:98)\r\n" + 
			"	at com.test.platform.orchestrator.core.queue.BaseQueueMessageHandler.handleMessage(BaseQueueMessageHandler.java:86)\r\n" + 
			"	at com.test.platform.orchestrator.core.queue.AbstractHandleMessageAction.handleMessageByHandler(AbstractHandleMessageAction.java:32)\r\n" + 
			"	at com.test.platform.orchestrator.core.queue.HandleMessageAction.handleMessageAndErrors(HandleMessageAction.java:50)\r\n" + 
			"	at com.test.platform.orchestrator.core.queue.HandleMessageAction.access$000(HandleMessageAction.java:16)\r\n" + 
			"	at com.test.platform.orchestrator.core.queue.HandleMessageAction$1.run(HandleMessageAction.java:39)\r\n" + 
			"	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)\r\n" + 
			"	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:146)\r\n" + 
			"	at weblogic.security.Security.runAs(Security.java:61)\r\n" + 
			"	at com.test.configuration.impl.weblogic.facets.WLSecurityFacet.doAs(WLSecurityFacet.java:46)\r\n" + 
			"	at com.test.configuration.compatibility.ConfigImpl.doAs(ConfigImpl.java:85)\r\n" + 
			"	at com.test.ejb.session.security.SecurityProcessor.doAsSystem(SecurityProcessor.java:55)\r\n" + 
			"	at com.test.platform.orchestrator.utils.KernelUtil.doAsSystem(KernelUtil.java:32)\r\n" + 
			"	at com.test.platform.orchestrator.core.queue.HandleMessageAction.handle(HandleMessageAction.java:35)\r\n" + 
			"	at com.test.platform.orchestrator.core.queue.MessageManager.handleMessage(MessageManager.java:107)\r\n" + 
			"	at com.test.platform.orchestrator.core.queue.OrchestrationQueueInvokerBean.handleMessage(OrchestrationQueueInvokerBean.java:59)\r\n" + 
			"	at com.test.platform.orchestrator.core.queue.OrchestrationQueueInvokerBean.handleMessage(OrchestrationQueueInvokerBean.java:37)\r\n" + 
			"	at com.test.platform.utils.tools.queueservice.QueueInvoker.handleMessage(QueueInvoker.java:108)\r\n" + 
			"	at com.test.platform.utils.tools.queueservice.QueueInvoker$1.handle(QueueInvoker.java:66)\r\n" + 
			"	at com.test.platform.utils.tools.queueservice.QueueService.handleMessage(QueueService.java:922)\r\n" + 
			"	at com.test.platform.utils.tools.queueservice.QueueService$4.processByCommonAlgorithm(QueueService.java:540)\r\n" + 
			"	at com.test.platform.utils.tools.queueservice.QueueService$4.executeServiceAction(QueueService.java:483)\r\n" + 
			"	at com.test.platform.utils.tools.queueservice.QueueService.executeTransactedAction(QueueService.java:889)\r\n" + 
			"	at com.test.platform.utils.tools.queueservice.QueueService.invokeOnQueueSegment(QueueService.java:445)\r\n" + 
			"	at com.test.platform.utils.tools.queueservice.QueueInvoker.processMessage(QueueInvoker.java:62)\r\n" + 
			"	at com.test.platform.utils.tools.queueservice.QueueInvoker.processMessage(QueueInvoker.java:47)\r\n" + 
			"	at com.test.platform.utils.tools.queueservice.QueueInvokerMDB.processMessage(QueueInvokerMDB.java:115)\r\n" + 
			"	at com.test.platform.utils.tools.queueservice.QueueInvokerMDB.onMessage(QueueInvokerMDB.java:71)\r\n" + 
			"	at weblogic.ejb.container.internal.MDListener.execute(MDListener.java:583)\r\n" + 
			"	at weblogic.ejb.container.internal.MDListener.transactionalOnMessage(MDListener.java:486)\r\n" + 
			"	at weblogic.ejb.container.internal.MDListener.onMessage(MDListener.java:388)\r\n" + 
			"	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:4817)\r\n" + 
			"	at weblogic.jms.client.JMSSession.execute(JMSSession.java:4491)\r\n" + 
			"	at weblogic.jms.client.JMSSession.executeMessage(JMSSession.java:3945)\r\n" + 
			"	at weblogic.jms.client.JMSSession.access$000(JMSSession.java:115)\r\n" + 
			"	at weblogic.jms.client.JMSSession$UseForRunnable.run(JMSSession.java:5337)\r\n" + 
			"	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:550)\r\n" + 
			"	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:263)\r\n" + 
			"	at weblogic.work.ExecuteThread.run(ExecuteThread.java:221)";
			
	public static final String FST_CAUSED_BY_1 = "com.test.salesorder.engine.business.impl.exception.exceptions.SoeUnexpectedBusinessException: java.lang.IllegalStateException: Price Guarantee Item 9154087675563809226 must have Add action instead of - if Price Guarantee Instance status is absentArguments"
			+ "\\nGot java.lang.IllegalStateException: Price Guarantee Item 9154087675563809226 must have Add action instead of - if Price Guarantee Instance status is absent "
			+ "\\nWhile execution(ActionResult com.test.salesorder.engine.business.impl.SalesOrderContextBusinessServiceImpl.doAction(SalesOrder,BaseActionParams)) "
			+ "\\nWith:"
			+ "\\n null\r\n" + 
			"ActionParams{actionName='legacy_get_salesorder', orderItemIds=null, targetOfferingIds=null, ruleElementIds=null, customerId=null, distributionChannelId=null, salesOrderId=9154084795413766140, discountItemIds=null, characteristic=null, priceValue=null, priceSpecId=null, bpiIds=null, statusChangeReason='null', reasonDescription='null', preview=false, typeOfSelling=null, pointAmount=null, count=null, billingAccountId=null, bpiIdMigrateTo=null, orderItemMigrateToId=null, locationIds=null, attachmentIds=null, attachmentDescriptorXmls=null, bulkCharacteristics=null, leadId=null, newTopForEveryChild=false, enableTestOfferings=null, nonAvailabilityCheck=null, proposalId=null, extendedCheckParams=null, targetLocationIds=null, rootBpiIds=null, extendedCheckParams=null, ignoreWarnings=null, exceptionResults=null, disableConfirmations=null, disableRules=null, cpeSerialNumber=null, cpeUnitAddress=null, cpeMacAddress=null, cpeSearchBy=null, cpeSearchParams=null, cpeSalesAction=null, cpeReturnReason=null, cpeItemIds=null, phoneNumberId=null, phoneNumberStr=null, phoneNumber1=null, phoneNumber2=null, contactName=null, overriddenNumberOfMins=null, techNumber=null, csrComment=null, extendPromotionPeriod=0, firstName=null, lastName=null, updatePhoneBook=false, temporaryDisconnect=false, effectiveDate=null, targetLocationFlag=false, revertAfterETFCalculated=false, commitmentETF=null, timeSlotId=null, fixedGridCellId=null, availableTime=0, availableTime=null, bulkPriceEvaluateLogic=false, bulkNrcPrice=-1.0, bulkMrcPrice=-1.0, timeSlotCode=null, firstAvailableAppointmentDate=null, isSalesOrderCanBeCanceled=false, initiatingSystem=null, parametricPriceOverride=false, suspensionMrcPerBPI=null, resumptionNrc=null, ignoreQuotaUpdate=false, isImmediateAction=false, propagatePhoneAction=false, currentSuspendRequestId= null, commentFromPortal= null, isSkipProhibitCpeModificationEarlyPonr= false, isAllowedPriceChange= false, cpeReturnReasonStr= null, workOrderId= null, isSendToServiceAgreement= false, easGeoCodeUpdateIsNeeded= false, notes= null}"
			+ "\r\n" + 
			"\r\n" + 
			"	at com.test.salesorder.engine.extension.impl.service.PriceGuaranteeItemActionCalculatorServiceImpl$3.apply(PriceGuaranteeItemActionCalculatorServiceImpl.java:104)\r\n" + 
			"	at com.test.salesorder.engine.extension.impl.service.PriceGuaranteeItemActionCalculatorServiceImpl$3.apply(PriceGuaranteeItemActionCalculatorServiceImpl.java:98)\r\n" + 
			"	at com.test.salesorder.engine.extension.impl.service.PriceGuaranteeItemActionCalculatorServiceImpl.tryGetPriceGuaranteeItemAction(PriceGuaranteeItemActionCalculatorServiceImpl.java:167)\r\n" + 
			"	at com.test.salesorder.engine.extension.impl.service.ChangePriceGuaranteeItemActionServiceImpl.changePriceGuaranteeItemAction(ChangePriceGuaranteeItemActionServiceImpl.java:43)\r\n" + 
			"	at com.test.salesorder.engine.extension.impl.service.PriceGuaranteeItemServiceImpl.removeOrDisconnectPriceGuaranteeItem(PriceGuaranteeItemServiceImpl.java:132)\r\n" + 
			"	at com.test.salesorder.engine.extension.impl.service.PriceGuaranteeItemServiceImpl.removePriceGuaranteeItemsOfOrderItem(PriceGuaranteeItemServiceImpl.java:121)\r\n" + 
			"	at com.test.salesorder.engine.extension.impl.service.DeleteOrderItemServiceImpl.removeOrderItemReferences(DeleteOrderItemServiceImpl.java:158)\r\n" + 
			"	at com.test.salesorder.engine.extension.impl.service.DeleteOrderItemServiceImpl.removePermanent(DeleteOrderItemServiceImpl.java:142)\r\n" + 
			"	at com.test.salesorder.engine.extension.impl.service.MergeSalesOrderServiceImpl.removeDashOrderItemsForDisconnectedBPIs(MergeSalesOrderServiceImpl.java:85)\r\n" + 
			"	at com.test.salesorder.engine.extension.impl.MergeNotConflictedOrderItemsProcessor.doAction(MergeNotConflictedOrderItemsProcessor.java:63)\r\n" + 
			"	at com.test.salesorder.engine.extension.impl.MergeNotConflictedOrderItemsProcessor.doAction(MergeNotConflictedOrderItemsProcessor.java:31)\r\n" + 
			"	at com.test.salesorder.engine.extension.api.AbstractExtendedActionProcessor.process(AbstractExtendedActionProcessor.java:119)\r\n" + 
			"	at com.test.salesorder.engine.business.impl.SalesOrderContextBusinessServiceImpl.processChain(SalesOrderContextBusinessServiceImpl.java:269)\r\n" + 
			"	at com.test.salesorder.engine.business.impl.SalesOrderContextBusinessServiceImpl.doAction(SalesOrderContextBusinessServiceImpl.java:160)\r\n" + 
			"	at com.test.salesorder.engine.business.impl.SalesOrderContextBusinessServiceImpl.doAction(SalesOrderContextBusinessServiceImpl.java:453)\r\n" + 
			"	at com.test.salesorder.engine.business.impl.SalesOrderContextBusinessServiceImpl$$FastClassBySpringCGLIB$$9f842d7f.invoke(&lt;generated&gt;)\r\n" + 
			"	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)\r\n" + 
			"	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)\r\n" + 
			"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)\r\n" + 
			"	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:58)\r\n" + 
			"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\r\n" + 
			"	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)\r\n" + 
			"	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:267)\r\n" + 
			"	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)\r\n" + 
			"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\r\n" + 
			"	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)\r\n" + 
			"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\r\n" + 
			"	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)\r\n" + 
			"	at com.test.salesorder.engine.business.impl.SalesOrderContextBusinessServiceImpl$$EnhancerBySpringCGLIB$$4ce7dfe.doAction(&lt;generated&gt;)\r\n" + 
			"	at com.test.solutions.cogeco.soe.service.impl.CogecoSalesOrderContextBusinessServiceImpl.doAction(CogecoSalesOrderContextBusinessServiceImpl.java:43)\r\n" + 
			"	at com.test.solutions.cogeco.soe.service.impl.CogecoSalesOrderContextBusinessServiceImpl$$FastClassBySpringCGLIB$$2d7ab401.invoke(&lt;generated&gt;)\r\n" + 
			"	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)\r\n" + 
			"	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)\r\n" + 
			"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)\r\n" + 
			"	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:58)\r\n" + 
			"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\r\n" + 
			"	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)\r\n" + 
			"	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:267)\r\n" + 
			"	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)\r\n" + 
			"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\r\n" + 
			"	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)\r\n" + 
			"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\r\n" + 
			"	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)\r\n" + 
			"	at com.test.solutions.cogeco.soe.service.impl.CogecoSalesOrderContextBusinessServiceImpl$$EnhancerBySpringCGLIB$$6b408640.doAction(&lt;generated&gt;)\r\n" + 
			"	at com.test.salesorder.engine.business.impl.SalesOrderLegacyServiceImpl.getSalesOrder(SalesOrderLegacyServiceImpl.java:95)\r\n" + 
			"	at com.test.salesorder.engine.business.impl.SalesOrderLegacyServiceImpl$$FastClassBySpringCGLIB$$1661b1b3.invoke(&lt;generated&gt;)\r\n" + 
			"	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)\r\n" + 
			"	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)\r\n" + 
			"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)\r\n" + 
			"	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:58)\r\n" + 
			"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\r\n" + 
			"	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)\r\n" + 
			"	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:267)\r\n" + 
			"	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)\r\n" + 
			"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\r\n" + 
			"	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)\r\n" + 
			"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\r\n" + 
			"	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)\r\n" + 
			"	at com.test.salesorder.engine.business.impl.SalesOrderLegacyServiceImpl$$EnhancerBySpringCGLIB$$672474f4.getSalesOrder(&lt;generated&gt;)\r\n" + 
			"	at com.test.roe.rest.datasource.CancelSalesOrderDS.cancelSalesOrder(CancelSalesOrderDS.java:91)\r\n" + 
			"	at com.test.solutions.cogeco.roe.rest.datasource.CogecoCancelSalesOrderDS.cancelSalesOrder(CogecoCancelSalesOrderDS.java:128)\r\n" + 
			"	at com.test.roe.rest.datasource.CancelSalesOrderDS.saveData(CancelSalesOrderDS.java:68)\r\n" + 
			"	at com.test.solutions.cogeco.roe.rest.datasource.CogecoCancelSalesOrderDS.saveData(CogecoCancelSalesOrderDS.java:429)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.actions.SaveAction.process(SaveAction.java:66)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.actions.transport.ActionsService.performAction(ActionsService.java:132)\r\n" + 
			"	at sun.reflect.GeneratedMethodAccessor4215.invoke(Unknown Source)\r\n" + 
			"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n" + 
			"	at java.lang.reflect.Method.invoke(Method.java:498)\r\n" + 
			"	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)\r\n" + 
			"	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)\r\n" + 
			"	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)\r\n" + 
			"	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)\r\n" + 
			"	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)\r\n" + 
			"	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)\r\n" + 
			"	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)\r\n" + 
			"	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)\r\n" + 
			"	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)\r\n" + 
			"	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)\r\n" + 
			"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:844)\r\n" + 
			"	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:280)\r\n" + 
			"	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:254)\r\n" + 
			"	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:136)\r\n" + 
			"	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:346)\r\n" + 
			"	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.cihm.web.rest.errorhandling.ServletInputLoggerFilter.doFilter(ServletInputLoggerFilter.java:42)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter$1.call(SecurityFilter.java:91)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter$1.call(SecurityFilter.java:88)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.doTxRequiresNew(TxUtils.java:319)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.doTxRequired(TxUtils.java:181)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.executeWith(TxUtils.java:80)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.executeWith(TxUtils.java:110)\r\n" + 
			"	at com.test.framework.transactions.TransactionAttribute.execute(TransactionAttribute.java:71)\r\n" + 
			"	at com.test.framework.transactions.TransactionAttribute.executeAndUnwrap(TransactionAttribute.java:87)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter.pass(SecurityFilter.java:88)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter.access$000(SecurityFilter.java:42)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter$2.run(SecurityFilter.java:130)\r\n" + 
			"	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:365)\r\n" + 
			"	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:146)\r\n" + 
			"	at weblogic.security.Security.runAs(Security.java:61)\r\n" + 
			"	at com.test.configuration.impl.weblogic.facets.WLSecurityFacet.doAs(WLSecurityFacet.java:46)\r\n" + 
			"	at com.test.configuration.compatibility.ConfigImpl.doAs(ConfigImpl.java:85)\r\n" + 
			"	at com.test.security.UserSession.doTask(UserSession.java:314)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter.doFilter(SecurityFilter.java:127)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.planetj.servlet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:270)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.security.oauth.server.filter.AuthorizedRequestsFilter.pass(AuthorizedRequestsFilter.java:137)\r\n" + 
			"	at com.test.security.oauth.server.filter.AuthorizedRequestsFilter.doFilter(AuthorizedRequestsFilter.java:117)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.mediation.dataflow.impl.core.pipes.ServletRuntimeRegister.doFilter(ServletRuntimeRegister.java:69)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.mediation.dataflow.impl.util.trigger.http.FilterImpl.doFilter(FilterImpl.java:126)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.core.filters.security.sessions.SessionHijackingFilter.doFilter(SessionHijackingFilter.java:75)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.core.filters.security.HttpSecurityFilter.doFilterInternal(HttpSecurityFilter.java:71)\r\n" + 
			"	at com.test.platform.core.filters.security.HttpSecurityFilter.doFilter(HttpSecurityFilter.java:53)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.core.filters.clientaddress.ClientAddressFilter.doFilter(ClientAddressFilter.java:89)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.jsp.statistics.StatisticsFilter.doFilter(StatisticsFilter.java:72)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.jsp.filters.SecurityHeaderFilter.doFilter(SecurityHeaderFilter.java:65)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.jsp.csrf.CSRFGuardFilter.doFilter(CSRFGuardFilter.java:180)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.filters.PollingFilter.doFilter(PollingFilter.java:54)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.framework.domain.filters.ThreadDomainFilter.doFilter(ThreadDomainFilter.java:87)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.presentation.process.SessionTouchFilter.doFilter(SessionTouchFilter.java:74)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.jsp.filters.ServletExceptionUnpackFilter.doFilter(ServletExceptionUnpackFilter.java:65)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:27)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3456)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3422)\r\n" + 
			"	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:323)\r\n" + 
			"	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)\r\n" + 
			"	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2280)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2196)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2174)\r\n" + 
			"	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1632)\r\n" + 
			"	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:256)\r\n" + 
			"	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)\r\n" + 
			"	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)\r\n" + 
			"Caused by: java.lang.IllegalStateException: Price Guarantee Item 9154087675563809226 must have Add action instead of - if Price Guarantee Instance status is absent\r\n" + 
			"	... 155 more";
			
	public static final String FST_CAUSED_BY_2 ="java.lang.RuntimeException: Error during request processing with timeout\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.CtrlService.processWithTimeout(CtrlService.java:139)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.CtrlService.refreshData(CtrlService.java:89)\r\n" + 
			"	at sun.reflect.GeneratedMethodAccessor4341.invoke(Unknown Source)\r\n" + 
			"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n" + 
			"	at java.lang.reflect.Method.invoke(Method.java:498)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.process.servicemethod.ServiceMethodProxy.invoke(ServiceMethodProxy.java:43)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.process.servicemethod.ServiceMethodProxyManager.invoke(ServiceMethodProxyManager.java:64)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.process.servicemethod.ServiceMethodRequestProcessorService.process(ServiceMethodRequestProcessorService.java:38)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.WidgetRequestProcessorService.processRequest(WidgetRequestProcessorService.java:184)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.WidgetRequestProcessorService.processWithTimeoutInternal(WidgetRequestProcessorService.java:147)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.WidgetRequestProcessorService.access$000(WidgetRequestProcessorService.java:58)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.WidgetRequestProcessorService$1.call(WidgetRequestProcessorService.java:97)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.WidgetRequestProcessorService$1.call(WidgetRequestProcessorService.java:94)\r\n" + 
			"	at com.test.framework.timeouts.TimeoutTracker.execute(TimeoutTracker.java:104)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.WidgetRequestProcessorService.processWithTimeout(WidgetRequestProcessorService.java:94)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.WidgetRequestProcessorService.process(WidgetRequestProcessorService.java:80)\r\n" + 
			"	at sun.reflect.GeneratedMethodAccessor4679.invoke(Unknown Source)\r\n" + 
			"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n" + 
			"	at java.lang.reflect.Method.invoke(Method.java:498)\r\n" + 
			"	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)\r\n" + 
			"	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)\r\n" + 
			"	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)\r\n" + 
			"	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)\r\n" + 
			"	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)\r\n" + 
			"	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)\r\n" + 
			"	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)\r\n" + 
			"	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)\r\n" + 
			"	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)\r\n" + 
			"	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)\r\n" + 
			"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:844)\r\n" + 
			"	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:280)\r\n" + 
			"	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:254)\r\n" + 
			"	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:136)\r\n" + 
			"	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:346)\r\n" + 
			"	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.cihm.web.rest.errorhandling.ServletInputLoggerFilter.doFilter(ServletInputLoggerFilter.java:42)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter$1.call(SecurityFilter.java:91)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter$1.call(SecurityFilter.java:88)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.doTxRequiresNew(TxUtils.java:319)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.doTxRequired(TxUtils.java:181)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.executeWith(TxUtils.java:80)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.executeWith(TxUtils.java:110)\r\n" + 
			"	at com.test.framework.transactions.TransactionAttribute.execute(TransactionAttribute.java:71)\r\n" + 
			"	at com.test.framework.transactions.TransactionAttribute.executeAndUnwrap(TransactionAttribute.java:87)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter.pass(SecurityFilter.java:88)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter.access$000(SecurityFilter.java:42)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter$2.run(SecurityFilter.java:130)\r\n" + 
			"	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:365)\r\n" + 
			"	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:146)\r\n" + 
			"	at weblogic.security.Security.runAs(Security.java:61)\r\n" + 
			"	at com.test.configuration.impl.weblogic.facets.WLSecurityFacet.doAs(WLSecurityFacet.java:46)\r\n" + 
			"	at com.test.configuration.compatibility.ConfigImpl.doAs(ConfigImpl.java:85)\r\n" + 
			"	at com.test.security.UserSession.doTask(UserSession.java:314)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter.doFilter(SecurityFilter.java:127)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.planetj.servlet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:270)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.security.oauth.server.filter.AuthorizedRequestsFilter.pass(AuthorizedRequestsFilter.java:137)\r\n" + 
			"	at com.test.security.oauth.server.filter.AuthorizedRequestsFilter.doFilter(AuthorizedRequestsFilter.java:117)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.mediation.dataflow.impl.core.pipes.ServletRuntimeRegister.doFilter(ServletRuntimeRegister.java:69)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.mediation.dataflow.impl.util.trigger.http.FilterImpl.doFilter(FilterImpl.java:126)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.core.filters.security.sessions.SessionHijackingFilter.doFilter(SessionHijackingFilter.java:75)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.core.filters.security.HttpSecurityFilter.doFilterInternal(HttpSecurityFilter.java:71)\r\n" + 
			"	at com.test.platform.core.filters.security.HttpSecurityFilter.doFilter(HttpSecurityFilter.java:53)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.core.filters.clientaddress.ClientAddressFilter.doFilter(ClientAddressFilter.java:89)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.jsp.statistics.StatisticsFilter.doFilter(StatisticsFilter.java:72)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.jsp.filters.SecurityHeaderFilter.doFilter(SecurityHeaderFilter.java:65)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.jsp.csrf.CSRFGuardFilter.doFilter(CSRFGuardFilter.java:180)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.filters.PollingFilter.doFilter(PollingFilter.java:54)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.framework.domain.filters.ThreadDomainFilter.doFilter(ThreadDomainFilter.java:87)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.presentation.process.SessionTouchFilter.doFilter(SessionTouchFilter.java:74)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.jsp.filters.ServletExceptionUnpackFilter.doFilter(ServletExceptionUnpackFilter.java:65)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:27)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3456)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3422)\r\n" + 
			"	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:323)\r\n" + 
			"	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)\r\n" + 
			"	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2280)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2196)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2174)\r\n" + 
			"	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1632)\r\n" + 
			"	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:256)\r\n" + 
			"	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)\r\n" + 
			"	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)\r\n" + 
			"Caused by: java.lang.RuntimeException: com.test.framework.jdbc.DataAccessException: Error due to access to database: \r\n" + 
			"	at com.test.jsp.dashboard.widgets.rest.configuration.WidgetConfigProvider.setupToolbars(WidgetConfigProvider.java:221)\r\n" + 
			"	at com.test.jsp.dashboard.widgets.rest.configuration.WidgetConfigProvider.setupConfig(WidgetConfigProvider.java:92)\r\n" + 
			"	at com.test.jsp.dashboard.widgets.rest.configuration.WidgetConfigFieldsProvider.setupConfig(WidgetConfigFieldsProvider.java:113)\r\n" + 
			"	at com.test.jsp.dashboard.widgets.rest.configuration.TableCtrlConfigProvider.setupConfig(TableCtrlConfigProvider.java:253)\r\n" + 
			"	at com.test.jsp.dashboard.widgets.rest.configuration.TableCtrlConfigProvider.setupConfig(TableCtrlConfigProvider.java:66)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.UniCtrlDS.getConfig(UniCtrlDS.java:114)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.BaseCtrlDS.process(BaseCtrlDS.java:36)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.TableCtrlDS.process(TableCtrlDS.java:88)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.TableCtrlDS.process(TableCtrlDS.java:71)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.CtrlService$1.call(CtrlService.java:111)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.CtrlService$1.call(CtrlService.java:101)\r\n" + 
			"	at com.test.framework.timeouts.TimeoutTracker.execute(TimeoutTracker.java:104)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.CtrlService.processWithTimeout(CtrlService.java:100)\r\n" + 
			"	... 105 more\r\n" + 
			"Caused by: com.test.framework.jdbc.DataAccessException: Error due to access to database: \r\n" + 
			"	at com.test.framework.jdbc.JDBCTemplates.execute(JDBCTemplates.java:174)\r\n" + 
			"	at com.test.framework.jdbc.JDBCTemplates.execute(JDBCTemplates.java:197)\r\n" + 
			"	at com.test.framework.jdbc.JDBCTemplates.execute(JDBCTemplates.java:249)\r\n" + 
			"	at com.test.framework.jdbc.JDBCTemplates.executeSelect(JDBCTemplates.java:295)\r\n" + 
			"	at com.test.platform.core.ncdo.model.dataobject.impl.NCDataObjectHelper.loadObjectTypes(NCDataObjectHelper.java:207)\r\n" + 
			"	at com.test.platform.core.ncdo.plugin.AbstractNCObjectPlugin.getObjectTypesByObjectIds(AbstractNCObjectPlugin.java:152)\r\n" + 
			"	at com.test.platform.core.ncdo.plugin.impl.resolver.DefaultCandidateResolver.resolveByElements(DefaultCandidateResolver.java:176)\r\n" + 
			"	at com.test.platform.core.ncdo.plugin.impl.resolver.DefaultCandidateResolver.resolveByElements(DefaultCandidateResolver.java:126)\r\n" + 
			"	at com.test.platform.core.ncdo.plugin.impl.resolver.DefaultCandidateResolver.resolveByObjectIds(DefaultCandidateResolver.java:72)\r\n" + 
			"	at com.test.platform.core.ncdo.plugin.impl.resolver.DefaultPluginsResolver.resolvePluginsByObjectIds(DefaultPluginsResolver.java:69)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.cache.impl.CachingAdapterImpl.resolvePluginsForKeysToLoad(CachingAdapterImpl.java:159)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.cache.impl.CachingAdapterImpl.filter(CachingAdapterImpl.java:123)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.loadObjects(RecourciveLoadingAdapter.java:330)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl.getObjectsInternal(PersistenceContextWithAutoCommitImpl.java:467)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl.getObjectsInternal(PersistenceContextWithAutoCommitImpl.java:456)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl_$$_jvst29a_1._d92getObjectsInternal(PersistenceContextWithAutoCommitImpl_$$_jvst29a_1.java)\r\n" + 
			"	at sun.reflect.GeneratedMethodAccessor750.invoke(Unknown Source)\r\n" + 
			"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n" + 
			"	at java.lang.reflect.Method.invoke(Method.java:498)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$InterceptedMethodInvocation.proceed(ProxyClassGenerator.java:196)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.interceptor.TxSynchronizedInterceptor.invoke(TxSynchronizedInterceptor.java:46)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$InterceptedMethodInvocation.proceed(ProxyClassGenerator.java:197)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$DelegatingInvocationHandler.invoke(ProxyClassGenerator.java:154)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl_$$_jvst29a_1.getObjectsInternal(PersistenceContextWithAutoCommitImpl_$$_jvst29a_1.java)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl.getObjectByID(PersistenceContextWithAutoCommitImpl.java:389)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl_$$_jvst29a_1._d72getObjectByID(PersistenceContextWithAutoCommitImpl_$$_jvst29a_1.java)\r\n" + 
			"	at sun.reflect.GeneratedMethodAccessor749.invoke(Unknown Source)\r\n" + 
			"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n" + 
			"	at java.lang.reflect.Method.invoke(Method.java:498)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$InterceptedMethodInvocation.proceed(ProxyClassGenerator.java:196)\r\n" + 
			"	at com.test.platform.core.ncdo.security.interceptor.AbstractSecurityInterceptor.invoke(AbstractSecurityInterceptor.java:38)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$InterceptedMethodInvocation.proceed(ProxyClassGenerator.java:197)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.interceptor.TxSynchronizedInterceptor.invoke(TxSynchronizedInterceptor.java:46)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$InterceptedMethodInvocation.proceed(ProxyClassGenerator.java:197)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.interceptor.NotClosedInterceptor.invoke(NotClosedInterceptor.java:35)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$InterceptedMethodInvocation.proceed(ProxyClassGenerator.java:197)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$DelegatingInvocationHandler.invoke(ProxyClassGenerator.java:154)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl_$$_jvst29a_1.getObjectByID(PersistenceContextWithAutoCommitImpl_$$_jvst29a_1.java)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl.getObjectByID(PersistenceContextWithAutoCommitImpl.java:89)\r\n" + 
			"	at com.test.jsp.dashboard.widgets.rest.configuration.WidgetConfigProvider.createContext(WidgetConfigProvider.java:317)\r\n" + 
			"	at com.test.jsp.dashboard.widgets.rest.configuration.WidgetConfigProvider.setupToolbars(WidgetConfigProvider.java:208)\r\n" + 
			"	... 117 more\r\n" + 
			"Caused by: java.sql.SQLException: Transaction BEA1-53EEE8AC402327B9D231 not active anymore. tx status = Marked rollback. [Reason=java.lang.RuntimeException: Error during request processing with timeout\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.CtrlService.processWithTimeout(CtrlService.java:139)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.CtrlService.refreshData(CtrlService.java:89)\r\n" + 
			"	at sun.reflect.GeneratedMethodAccessor4341.invoke(Unknown Source)\r\n" + 
			"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n" + 
			"	at java.lang.reflect.Method.invoke(Method.java:498)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.process.servicemethod.ServiceMethodProxy.invoke(ServiceMethodProxy.java:43)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.process.servicemethod.ServiceMethodProxyManager.invoke(ServiceMethodProxyManager.java:64)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.process.servicemethod.ServiceMethodRequestProcessorService.process(ServiceMethodRequestProcessorService.java:38)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.WidgetRequestProcessorService.processRequest(WidgetRequestProcessorService.java:184)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.WidgetRequestProcessorService.processWithTimeoutInternal(WidgetRequestProcessorService.java:147)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.WidgetRequestProcessorService.access$000(WidgetRequestProcessorService.java:58)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.WidgetRequestProcessorService$1.call(WidgetRequestProcessorService.java:97)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.WidgetRequestProcessorService$1.call(WidgetRequestProcessorService.java:94)\r\n" + 
			"	at com.test.framework.timeouts.TimeoutTracker.execute(TimeoutTracker.java:104)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.WidgetRequestProcessorService.processWithTimeout(WidgetRequestProcessorService.java:94)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.WidgetRequestProcessorService.process(WidgetRequestProcessorService.java:80)\r\n" + 
			"	at sun.reflect.GeneratedMethodAccessor4679.invoke(Unknown Source)\r\n" + 
			"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n" + 
			"	at java.lang.reflect.Method.invoke(Method.java:498)\r\n" + 
			"	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)\r\n" + 
			"	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)\r\n" + 
			"	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)\r\n" + 
			"	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)\r\n" + 
			"	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)\r\n" + 
			"	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)\r\n" + 
			"	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)\r\n" + 
			"	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)\r\n" + 
			"	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)\r\n" + 
			"	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)\r\n" + 
			"	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)\r\n" + 
			"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:844)\r\n" + 
			"	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:280)\r\n" + 
			"	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:254)\r\n" + 
			"	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:136)\r\n" + 
			"	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:346)\r\n" + 
			"	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.cihm.web.rest.errorhandling.ServletInputLoggerFilter.doFilter(ServletInputLoggerFilter.java:42)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter$1.call(SecurityFilter.java:91)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter$1.call(SecurityFilter.java:88)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.doTxRequiresNew(TxUtils.java:319)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.doTxRequired(TxUtils.java:181)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.executeWith(TxUtils.java:80)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.executeWith(TxUtils.java:110)\r\n" + 
			"	at com.test.framework.transactions.TransactionAttribute.execute(TransactionAttribute.java:71)\r\n" + 
			"	at com.test.framework.transactions.TransactionAttribute.executeAndUnwrap(TransactionAttribute.java:87)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter.pass(SecurityFilter.java:88)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter.access$000(SecurityFilter.java:42)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter$2.run(SecurityFilter.java:130)\r\n" + 
			"	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:365)\r\n" + 
			"	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:146)\r\n" + 
			"	at weblogic.security.Security.runAs(Security.java:61)\r\n" + 
			"	at com.test.configuration.impl.weblogic.facets.WLSecurityFacet.doAs(WLSecurityFacet.java:46)\r\n" + 
			"	at com.test.configuration.compatibility.ConfigImpl.doAs(ConfigImpl.java:85)\r\n" + 
			"	at com.test.security.UserSession.doTask(UserSession.java:314)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.SecurityFilter.doFilter(SecurityFilter.java:127)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.planetj.servlet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:270)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.security.oauth.server.filter.AuthorizedRequestsFilter.pass(AuthorizedRequestsFilter.java:137)\r\n" + 
			"	at com.test.security.oauth.server.filter.AuthorizedRequestsFilter.doFilter(AuthorizedRequestsFilter.java:117)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.mediation.dataflow.impl.core.pipes.ServletRuntimeRegister.doFilter(ServletRuntimeRegister.java:69)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.mediation.dataflow.impl.util.trigger.http.FilterImpl.doFilter(FilterImpl.java:126)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.core.filters.security.sessions.SessionHijackingFilter.doFilter(SessionHijackingFilter.java:75)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.core.filters.security.HttpSecurityFilter.doFilterInternal(HttpSecurityFilter.java:71)\r\n" + 
			"	at com.test.platform.core.filters.security.HttpSecurityFilter.doFilter(HttpSecurityFilter.java:53)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.core.filters.clientaddress.ClientAddressFilter.doFilter(ClientAddressFilter.java:89)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.jsp.statistics.StatisticsFilter.doFilter(StatisticsFilter.java:72)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.jsp.filters.SecurityHeaderFilter.doFilter(SecurityHeaderFilter.java:65)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.jsp.csrf.CSRFGuardFilter.doFilter(CSRFGuardFilter.java:180)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.filters.PollingFilter.doFilter(PollingFilter.java:54)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.framework.domain.filters.ThreadDomainFilter.doFilter(ThreadDomainFilter.java:87)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.presentation.process.SessionTouchFilter.doFilter(SessionTouchFilter.java:74)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at com.test.jsp.filters.ServletExceptionUnpackFilter.doFilter(ServletExceptionUnpackFilter.java:65)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:27)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3456)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3422)\r\n" + 
			"	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:323)\r\n" + 
			"	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)\r\n" + 
			"	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2280)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2196)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2174)\r\n" + 
			"	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1632)\r\n" + 
			"	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:256)\r\n" + 
			"	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)\r\n" + 
			"	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)\r\n" + 
			"Caused by: com.test.framework.transactions.TxException: java.lang.RuntimeException: java.util.ConcurrentModificationException\r\n" + 
			"	at com.test.framework.transactions.TxUtils.doTxRequired(TxUtils.java:197)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.doTxRequired(TxUtils.java:214)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.UniCtrlDS.fetchData(UniCtrlDS.java:353)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.TableCtrlDS.fetchData(TableCtrlDS.java:267)\r\n" + 
			"	at com.test.jsp.dashboard.widgets.rest.service.WidgetTableCtrlDS.fetchData(WidgetTableCtrlDS.java:161)\r\n" + 
			"	at com.test.cihm.web.rest.service.plaintable.PlainTableCtrlFetchPlanDS.fetchData(PlainTableCtrlFetchPlanDS.java:34)\r\n" + 
			"	at com.test.cihm.web.rest.service.plaintable.PlainTableCtrlFetchPlanDS.fetchData(PlainTableCtrlFetchPlanDS.java:23)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.BaseCtrlDS.process(BaseCtrlDS.java:38)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.TableCtrlDS.process(TableCtrlDS.java:88)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.TableCtrlDS.process(TableCtrlDS.java:71)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.CtrlService$1.call(CtrlService.java:111)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.CtrlService$1.call(CtrlService.java:101)\r\n" + 
			"	at com.test.framework.timeouts.TimeoutTracker.execute(TimeoutTracker.java:104)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.transport.CtrlService.processWithTimeout(CtrlService.java:100)\r\n" + 
			"	... 105 more\r\n" + 
			"Caused by: java.lang.RuntimeException: java.util.ConcurrentModificationException\r\n" + 
			"	at com.test.platform.core.ncdo.model.dataobject.loading.NCObjectsBulkLoadManager.loadObjects(NCObjectsBulkLoadManager.java:82)\r\n" + 
			"	at com.test.platform.core.ncdo.model.dataobject.loading.InternalLoadingFacade.loadObjects(InternalLoadingFacade.java:68)\r\n" + 
			"	at com.test.platform.core.ncdo.plugin.impl.NCObjectPlugin.loadObjects(NCObjectPlugin.java:98)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.DefaultPluginOverrider.loadObjects(DefaultPluginOverrider.java:69)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.loadObjectsInIteration(RecourciveLoadingAdapter.java:653)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.loadObjectsByFetchPlans(RecourciveLoadingAdapter.java:559)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.recoursiveLoad(RecourciveLoadingAdapter.java:535)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.recoursiveLoad(RecourciveLoadingAdapter.java:548)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.loadObjectsByFetchPlans(RecourciveLoadingAdapter.java:562)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.recoursiveLoad(RecourciveLoadingAdapter.java:535)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.recoursiveLoad(RecourciveLoadingAdapter.java:548)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.loadObjectsByFetchPlans(RecourciveLoadingAdapter.java:562)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.recoursiveLoad(RecourciveLoadingAdapter.java:535)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.recoursiveLoad(RecourciveLoadingAdapter.java:548)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.loadObjectsByFetchPlans(RecourciveLoadingAdapter.java:562)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.recoursiveLoad(RecourciveLoadingAdapter.java:535)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.loadObjects(RecourciveLoadingAdapter.java:381)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.RecourciveLoadingAdapter.loadObjects(RecourciveLoadingAdapter.java:331)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl.getObjectsInternal(PersistenceContextWithAutoCommitImpl.java:467)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl.getObjectsInternal(PersistenceContextWithAutoCommitImpl.java:456)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl_$$_jvst29a_1._d92getObjectsInternal(PersistenceContextWithAutoCommitImpl_$$_jvst29a_1.java)\r\n" + 
			"	at sun.reflect.GeneratedMethodAccessor750.invoke(Unknown Source)\r\n" + 
			"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n" + 
			"	at java.lang.reflect.Method.invoke(Method.java:498)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$InterceptedMethodInvocation.proceed(ProxyClassGenerator.java:196)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.interceptor.TxSynchronizedInterceptor.invoke(TxSynchronizedInterceptor.java:46)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$InterceptedMethodInvocation.proceed(ProxyClassGenerator.java:197)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$DelegatingInvocationHandler.invoke(ProxyClassGenerator.java:154)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl_$$_jvst29a_1.getObjectsInternal(PersistenceContextWithAutoCommitImpl_$$_jvst29a_1.java)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl.getObjectByID(PersistenceContextWithAutoCommitImpl.java:389)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl_$$_jvst29a_1._d72getObjectByID(PersistenceContextWithAutoCommitImpl_$$_jvst29a_1.java)\r\n" + 
			"	at sun.reflect.GeneratedMethodAccessor749.invoke(Unknown Source)\r\n" + 
			"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n" + 
			"	at java.lang.reflect.Method.invoke(Method.java:498)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$InterceptedMethodInvocation.proceed(ProxyClassGenerator.java:196)\r\n" + 
			"	at com.test.platform.core.ncdo.security.interceptor.AbstractSecurityInterceptor.invoke(AbstractSecurityInterceptor.java:38)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$InterceptedMethodInvocation.proceed(ProxyClassGenerator.java:197)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.interceptor.TxSynchronizedInterceptor.invoke(TxSynchronizedInterceptor.java:46)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$InterceptedMethodInvocation.proceed(ProxyClassGenerator.java:197)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.interceptor.NotClosedInterceptor.invoke(NotClosedInterceptor.java:35)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$InterceptedMethodInvocation.proceed(ProxyClassGenerator.java:197)\r\n" + 
			"	at com.test.platform.core.ncdo.security.util.ProxyClassGenerator$DelegatingInvocationHandler.invoke(ProxyClassGenerator.java:154)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl_$$_jvst29a_1.getObjectByID(PersistenceContextWithAutoCommitImpl_$$_jvst29a_1.java)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl.getObjectById(PersistenceContextWithAutoCommitImpl.java:1396)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.impl.PersistenceContextWithAutoCommitImpl.getObjectById(PersistenceContextWithAutoCommitImpl.java:89)\r\n" + 
			"	at com.test.cihm.app.logic.utils.PlainTableObjectUtils$1.execute(PlainTableObjectUtils.java:94)\r\n" + 
			"	at com.test.cihm.app.logic.utils.PlainTableObjectUtils$1.execute(PlainTableObjectUtils.java:91)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.management.PCUtils.performAction(PCUtils.java:158)\r\n" + 
			"	at com.test.platform.core.ncdo.persistence.management.PCUtils.performAction(PCUtils.java:208)\r\n" + 
			"	at com.test.cihm.app.logic.utils.PCUtils.doAction(PCUtils.java:145)\r\n" + 
			"	at com.test.cihm.app.logic.utils.PlainTableObjectUtils.composePlainObjectUrl(PlainTableObjectUtils.java:91)\r\n" + 
			"	at com.test.cihm.web.rest.service.plaintable.PlainTableUIReferenceCustomizer.specificCustomizeUrl(PlainTableUIReferenceCustomizer.java:41)\r\n" + 
			"	at com.test.cihm.web.rest.service.plaintable.PlainTableUIReferenceCustomizer.customizeUrl(PlainTableUIReferenceCustomizer.java:36)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.UIReferenceCustomizer.buildReferenceValueConfig(UIReferenceCustomizer.java:62)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.attribute.AttributeParser.processNameAttribute(AttributeParser.java:151)\r\n" + 
			"	at com.test.jsp.dashboard.widgets.rest.service.attribute.WidgetAttributeParser.processNameAttribute(WidgetAttributeParser.java:56)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.attribute.AttributeParser.fetchAttribute(AttributeParser.java:208)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.UniCtrlDS.fetchAttribute(UniCtrlDS.java:470)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.UniCtrlDS.setParametersFromUIDataObject(UniCtrlDS.java:458)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.TableCtrlDS.setFetchDataToResponse(TableCtrlDS.java:122)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.TableCtrlDS.setFetchDataToResponse(TableCtrlDS.java:71)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.UniCtrlDS.fetchDataResponse(UniCtrlDS.java:365)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.UniCtrlDS.access$000(UniCtrlDS.java:81)\r\n" + 
			"	at com.test.platform.ui.plugins.rest.service.datasources.UniCtrlDS$1.call(UniCtrlDS.java:347)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.doTxRequired(TxUtils.java:186)\r\n" + 
			"	... 118 more\r\n" + 
			"Caused by: java.util.ConcurrentModificationException\r\n" + 
			"	at java.util.TreeMap$PrivateEntryIterator.remove(TreeMap.java:1232)\r\n" + 
			"	at com.test.ejb.core.NCObjectBase.removeEmptyValues(NCObjectBase.java:1444)\r\n" + 
			"	at com.test.ejb.core.NCObjectBase.fillLocalizedData(NCObjectBase.java:1434)\r\n" + 
			"	at com.test.ejb.core.NCObjectBase.fillObjectByData(NCObjectBase.java:1416)\r\n" + 
			"	at com.test.ejb.core.light.NCObjectLight.&lt;init&gt;(NCObjectLight.java:81)\r\n" + 
			"	at com.test.platform.core.ncdo.model.dataobject.loading.ObjectsLoader.createNCObjectLight(ObjectsLoader.java:354)\r\n" + 
			"	at com.test.platform.core.ncdo.model.dataobject.loading.ObjectsLoader.createNCObjectLights(ObjectsLoader.java:346)\r\n" + 
			"	at com.test.platform.core.ncdo.model.dataobject.loading.ObjectsLoader.loadParametersFromNCObjectLight(ObjectsLoader.java:430)\r\n" + 
			"	at com.test.platform.core.ncdo.model.dataobject.loading.ObjectsLoader.loadByIDs(ObjectsLoader.java:113)\r\n" + 
			"	at com.test.platform.core.ncdo.model.dataobject.loading.NCObjectsBulkLoadManager.doLoadObjects(NCObjectsBulkLoadManager.java:124)\r\n" + 
			"	at com.test.platform.core.ncdo.model.dataobject.loading.NCObjectsBulkLoadManager.loadObjects(NCObjectsBulkLoadManager.java:71)\r\n" + 
			"	... 182 more\r\n" + 
			"]\r\n" + 
			"	at weblogic.jdbc.jts.Driver.getTransaction(Driver.java:556)\r\n" + 
			"	at weblogic.jdbc.jts.Driver.connect(Driver.java:113)\r\n" + 
			"	at weblogic.jdbc.common.internal.RmiDataSource.getConnectionInternal(RmiDataSource.java:589)\r\n" + 
			"	at weblogic.jdbc.common.internal.RmiDataSource.getConnection(RmiDataSource.java:545)\r\n" + 
			"	at weblogic.jdbc.common.internal.RmiDataSource.getConnection(RmiDataSource.java:538)\r\n" + 
			"	at com.test.framework.jdbc.JDBCTemplates.execute(JDBCTemplates.java:154)\r\n" + 
			"	... 157 more";
	public static final String FST_CAUSED_BY_3 ="ca.google.exception.base.ossj.OssjProcessingError: EJB Exception: : java.lang.RuntimeException: java.lang.RuntimeException: ca.google.exception.base.ossj.OssjProcessingError: There is processing order with this correlationId\r\n" + 
			"	at com.test.applications.ossjpp.util.PersistenceUtils.execute(PersistenceUtils.java:150)\r\n" + 
			"	at com.test.applications.ossjpp.om.facade.xbean.CreateRequestByValueWsOperation.execute(CreateRequestByValueWsOperation.java:31)\r\n" + 
			"	at com.test.applications.ossj.base.facade.WsOperationRunnerBean.executeOperation(WsOperationRunnerBean.java:43)\r\n" + 
			"	at com.test.applications.ossj.base.facade.WsOperationRunnerBeanLocal_ob4frp_ELOImpl.__WL_invoke(Unknown Source)\r\n" + 
			"	at weblogic.ejb.container.internal.SessionLocalMethodInvoker.invoke(SessionLocalMethodInvoker.java:39)\r\n" + 
			"	at com.test.applications.ossj.base.facade.WsOperationRunnerBeanLocal_ob4frp_ELOImpl.executeOperation(Unknown Source)\r\n" + 
			"	at com.test.applications.ossj.base.xbean.XmlBeansFacade.handle(XmlBeansFacade.java:245)\r\n" + 
			"	at com.test.applications.ossj.base.xbean.XmlBeansFacade.handleNode(XmlBeansFacade.java:280)\r\n" + 
			"	at com.test.applications.ossj.base.handler.XmlBeansHandler.handleRequest(XmlBeansHandler.java:203)\r\n" + 
			"	at com.test.applications.ossj.base.handler.GenericProxyHandler.handleRequest(GenericProxyHandler.java:232)\r\n" + 
			"	at weblogic.wsee.handler.JaxrpcHandlerChain.handleRequest(JaxrpcHandlerChain.java:58)\r\n" + 
			"	at weblogic.wsee.ws.dispatch.server.JaxrpcChainHandler.handleRequest(JaxrpcChainHandler.java:102)\r\n" + 
			"	at weblogic.wsee.handler.HandlerIterator.handleRequest(HandlerIterator.java:141)\r\n" + 
			"	at weblogic.wsee.ws.dispatch.server.ServerDispatcher.dispatch(ServerDispatcher.java:114)\r\n" + 
			"	at weblogic.wsee.ws.WsSkel.invoke(WsSkel.java:80)\r\n" + 
			"	at weblogic.wsee.server.servlet.SoapProcessor.handlePost(SoapProcessor.java:66)\r\n" + 
			"	at weblogic.wsee.server.servlet.SoapProcessor.process(SoapProcessor.java:44)\r\n" + 
			"	at weblogic.wsee.server.servlet.BaseWSServlet$AuthorizedInvoke.run(BaseWSServlet.java:285)\r\n" + 
			"	at weblogic.wsee.server.servlet.BaseWSServlet.service(BaseWSServlet.java:169)\r\n" + 
			"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)\r\n" + 
			"	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)\r\n" + 
			"	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)\r\n" + 
			"	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:301)\r\n" + 
			"	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:26)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:60)\r\n" + 
			"	at ca.google.utilities.ShawOssjSecurityCheckFilter.doFilter(ShawOssjSecurityCheckFilter.java:52)\r\n" + 
			"	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:60)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3748)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3714)\r\n" + 
			"	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)\r\n" + 
			"	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2283)\r\n" + 
			"	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2182)\r\n" + 
			"	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1499)\r\n" + 
			"	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:263)\r\n" + 
			"	at weblogic.work.ExecuteThread.run(ExecuteThread.java:221)\r\n" + 
			"Caused by: java.lang.RuntimeException: ca.google.exception.base.ossj.OssjProcessingError: There is processing order with this correlationId\r\n" + 
			"	at com.test.applications.ossjpp.om.facade.xbean.CreateRequestByValueWsOperation$1.execute(CreateRequestByValueWsOperation.java:42)\r\n" + 
			"	at com.test.applications.ossjpp.util.PersistenceUtils.execute(PersistenceUtils.java:145)\r\n" + 
			"	... 35 more\r\n" + 
			"Caused by: ca.google.exception.base.ossj.OssjProcessingError: There is processing order with this correlationId\r\n" + 
			"	at com.test.solutions.google.ossj.delegates.ServiceOrderDelegate.create(ServiceOrderDelegate.java:240)\r\n" + 
			"	at com.test.applications.ossj.om.common.processors.impl.CreateRequestsByValuesProcessor.process(CreateRequestsByValuesProcessor.java:63)\r\n" + 
			"	at com.test.applications.ossj.base.controller.AbstractBusinessController.invoke(AbstractBusinessController.java:64)\r\n" + 
			"	at com.test.applications.ossj.om.facade.xbean.CreateRequestByValueWsOperation.execute(CreateRequestByValueWsOperation.java:60)\r\n" + 
			"	at com.test.applications.ossjpp.om.facade.xbean.CreateRequestByValueWsOperation.access$001(CreateRequestByValueWsOperation.java:27)\r\n" + 
			"	at com.test.applications.ossjpp.om.facade.xbean.CreateRequestByValueWsOperation$1.execute(CreateRequestByValueWsOperation.java:38)\r\n" + 
			"	... 36 more\r\n" + 
			"Caused by: com.test.NCException: There is processing order with this correlationId\r\n" + 
			"	at com.test.ejb.session.security.SecurityProcessor.doAsSystem(SecurityProcessor.java:66)\r\n" + 
			"	at com.test.solutions.google.ossj.delegates.ServiceOrderDelegate.doAsSystem(ServiceOrderDelegate.java:124)\r\n" + 
			"	at com.test.solutions.google.ossj.delegates.ServiceOrderDelegate.create(ServiceOrderDelegate.java:140)\r\n" + 
			"	... 41 more\r\n" + 
			"Caused by: ca.google.exception.base.ossj.OssjDefaultShawRuntimeException: There is processing order with this correlationId\r\n" + 
			"	at com.test.solutions.google.ossj.delegates.ServiceOrderDelegate$1.run(ServiceOrderDelegate.java:206)\r\n" + 
			"	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)\r\n" + 
			"	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:146)\r\n" + 
			"	at weblogic.security.Security.runAs(Security.java:61)\r\n" + 
			"	at com.test.configuration.impl.weblogic.facets.WLSecurityFacet.doAs(WLSecurityFacet.java:46)\r\n" + 
			"	at com.test.configuration.compatibility.ConfigImpl.doAs(ConfigImpl.java:85)\r\n" + 
			"	at com.test.ejb.session.security.SecurityProcessor.doAsSystem(SecurityProcessor.java:55)\r\n" + 
			"	... 43 more\r\n" + 
			"\r\n" + 
			"\r\n" + 
			"	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\r\n" + 
			"	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)\r\n" + 
			"	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\r\n" + 
			"	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)\r\n" + 
			"	at ca.google.exception.base.ossj.OssjExceptionResolver.findExceptionByStackTrace(OssjExceptionResolver.java:40)\r\n" + 
			"	at com.test.solutions.google.ossj.OssjWebServiceClient.processResponse(OssjWebServiceClient.java:301)\r\n" + 
			"	at com.test.solutions.google.ossj.OssjWebServiceClient.processResponse(OssjWebServiceClient.java:146)\r\n" + 
			"	at com.test.solutions.google.ossj.OssjWebServiceClient.runWS(OssjWebServiceClient.java:114)\r\n" + 
			"	at ca.google.command.ossj.SendPreparedOSSJRequestCommand.getResponse(SendPreparedOSSJRequestCommand.java:67)\r\n" + 
			"	at ca.google.command.ossj.SendPreparedOSSJRequestCommand.execute(SendPreparedOSSJRequestCommand.java:43)\r\n" + 
			"	at ca.google.command.ossj.SendPreparedOSSJRequestCommand.execute(SendPreparedOSSJRequestCommand.java:21)\r\n" + 
			"	at ca.google.repository.util.CallableCommand.call(CallableCommand.java:19)\r\n" + 
			"	at ca.google.repository.util.PrivilegedAction.run(PrivilegedAction.java:17)\r\n" + 
			"	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)\r\n" + 
			"	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:146)\r\n" + 
			"	at weblogic.security.Security.runAs(Security.java:61)\r\n" + 
			"	at com.test.configuration.impl.weblogic.facets.WLSecurityFacet.doAs(WLSecurityFacet.java:46)\r\n" + 
			"	at com.test.configuration.compatibility.ConfigImpl.doAs(ConfigImpl.java:85)\r\n" + 
			"	at com.test.ejb.session.security.SecurityProcessor.doAsSystem(SecurityProcessor.java:55)\r\n" + 
			"	at ca.google.repository.util.SecurityHelper.executeAsSystem(SecurityHelper.java:54)\r\n" + 
			"	at ca.google.repository.util.SecurityContext.executeAsSystem(SecurityContext.java:9)\r\n" + 
			"	at ca.google.command.util.CommandExecutorImpl.execute(CommandExecutorImpl.java:28)\r\n" + 
			"	at ca.google.command.util.CommandExecutorImpl.execute(CommandExecutorImpl.java:24)\r\n" + 
			"	at ca.google.yahoointegration.AbstractWorkflowService.execute(AbstractWorkflowService.java:143)\r\n" + 
			"	at ca.google.som.yahoointegration.SomWorkflowService.access$301(SomWorkflowService.java:33)\r\n" + 
			"	at ca.google.som.yahoointegration.SomWorkflowService$1.call(SomWorkflowService.java:104)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.doTxRequiresNew(TxUtils.java:319)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.executeWith(TxUtils.java:78)\r\n" + 
			"	at com.test.framework.transactions.TxUtils.executeWith(TxUtils.java:110)\r\n" + 
			"	at com.test.framework.transactions.TransactionAttribute.execute(TransactionAttribute.java:71)\r\n" + 
			"	at com.test.framework.transactions.TransactionAttribute.executeAndUnwrap(TransactionAttribute.java:87)\r\n" + 
			"	at ca.google.util.transaction.TransactionManager.executeAndUnwrap(TransactionManager.java:178)\r\n" + 
			"	at ca.google.util.transaction.TransactionManager.executeAndUnwrap(TransactionManager.java:173)\r\n" + 
			"	at ca.google.som.yahoointegration.SomWorkflowService.execute(SomWorkflowService.java:97)\r\n" + 
			"	at ca.google.som.yahoointegration.SomWorkflowService.execute(SomWorkflowService.java:33)\r\n" + 
			"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n" + 
			"	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n" + 
			"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n" + 
			"	at java.lang.reflect.Method.invoke(Method.java:606)\r\n" + 
			"	at com.test.scripting.DefaultContext$MethodActionImpl.invoke(DefaultContext.java:330)\r\n" + 
			"	at com.test.scripting.Node$Action.invoke(Node.java:2286)\r\n" + 
			"	at com.test.scripting.Node$Function.execInternal(Node.java:2452)\r\n" + 
			"	at com.test.scripting.Node.execute(Node.java:115)\r\n" + 
			"	at com.test.scripting.Parser$EvaluatableImpl.evaluate(Parser.java:1703)\r\n" + 
			"	at com.test.scripting.Script.evaluateExpression(Script.java:230)\r\n" + 
			"	at com.test.scripting.Script.evaluateExpression(Script.java:159)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ActionProcessor.makeExpressionResult(ActionProcessor.java:223)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ActionProcessor.makeResult(ActionProcessor.java:98)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ActionProcessor.execute(ActionProcessor.java:133)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ActivitySectionManager.execute(ActivitySectionManager.java:95)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ActivitySectionManager.execute(ActivitySectionManager.java:65)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ProcessProxy.executeActivitySection(ProcessProxy.java:1284)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ProcessProxy$2.run(ProcessProxy.java:506)\r\n" + 
			"	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)\r\n" + 
			"	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:146)\r\n" + 
			"	at weblogic.security.Security.runAs(Security.java:61)\r\n" + 
			"	at com.test.configuration.impl.weblogic.facets.WLSecurityFacet.doAs(WLSecurityFacet.java:46)\r\n" + 
			"	at com.test.configuration.compatibility.ConfigImpl.doAs(ConfigImpl.java:85)\r\n" + 
			"	at com.test.ejb.session.security.SecurityProcessor.doAs(SecurityProcessor.java:85)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ProcessProxy.executeNextActivitySection(ProcessProxy.java:502)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ProcessProxy.executeProcess(ProcessProxy.java:379)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ProcessManagerBean.executeInTransaction(ProcessManagerBean.java:250)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ProcessManagerBean_cf75jw_EOImpl.__WL_invoke(Unknown Source)\r\n" + 
			"	at weblogic.ejb.container.internal.SessionRemoteMethodInvoker.invoke(SessionRemoteMethodInvoker.java:40)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ProcessManagerBean_cf75jw_EOImpl.executeInTransaction(Unknown Source)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ProcessManagerBean.execute(ProcessManagerBean.java:211)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ProcessManagerBean_cf75jw_EOImpl.__WL_invoke(Unknown Source)\r\n" + 
			"	at weblogic.ejb.container.internal.SessionRemoteMethodInvoker.invoke(SessionRemoteMethodInvoker.java:40)\r\n" + 
			"	at com.test.ejb.wf.engine.processor.ProcessManagerBean_cf75jw_EOImpl.execute(Unknown Source)\r\n" + 
			"	at com.test.ejb.wf.interface2.WfSubscriberSysJMSBean$1.run(WfSubscriberSysJMSBean.java:214)\r\n" + 
			"	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)\r\n" + 
			"	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:146)\r\n" + 
			"	at weblogic.security.Security.runAs(Security.java:61)\r\n" + 
			"	at com.test.configuration.impl.weblogic.facets.WLSecurityFacet.doAs(WLSecurityFacet.java:46)\r\n" + 
			"	at com.test.configuration.compatibility.ConfigImpl.doAs(ConfigImpl.java:85)\r\n" + 
			"	at com.test.ejb.session.security.SecurityProcessor.doAsSystem(SecurityProcessor.java:55)\r\n" + 
			"	at com.test.ejb.wf.interface2.WfSubscriberSysJMSBean.onMessage(WfSubscriberSysJMSBean.java:267)\r\n" + 
			"	at weblogic.ejb.container.internal.MDListener.execute(MDListener.java:583)\r\n" + 
			"	at weblogic.ejb.container.internal.MDListener.transactionalOnMessage(MDListener.java:486)\r\n" + 
			"	at weblogic.ejb.container.internal.MDListener.onMessage(MDListener.java:388)\r\n" + 
			"	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:4817)\r\n" + 
			"	at weblogic.jms.client.JMSSession.execute(JMSSession.java:4491)\r\n" + 
			"	at weblogic.jms.client.JMSSession.executeMessage(JMSSession.java:3945)\r\n" + 
			"	at weblogic.jms.client.JMSSession.access$000(JMSSession.java:115)\r\n" + 
			"	at weblogic.jms.client.JMSSession$UseForRunnable.run(JMSSession.java:5337)\r\n" + 
			"	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:550)\r\n" + 
			"	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:263)\r\n" + 
			"	at weblogic.work.ExecuteThread.run(ExecuteThread.java:221)";
	
}
